---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: clusterpolicies.transition.dcnlab.ssu.ac.kr
spec:
  group: transition.dcnlab.ssu.ac.kr
  names:
    kind: ClusterPolicy
    listKind: ClusterPolicyList
    plural: clusterpolicies
    singular: clusterpolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ClusterPolicy is the Schema for the clusterpolicies API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterPolicySpec defines the desired state of ClusterPolicy.
            properties:
              clusterSelector:
                description: ClusterSelector specifies the source cluster
                properties:
                  name:
                    type: string
                  provider:
                    type: string
                  repo:
                    type: string
                  repoType:
                    type: string
                required:
                - name
                - repo
                - repoType
                type: object
              packageSelectors:
                description: TransitionMode         string                 `json:"transitionMode"`
                  // manual, automatic, or none
                items:
                  description: PackageSelector defines individual package selection
                    criteria
                  properties:
                    backupInformation:
                      items:
                        properties:
                          backupType:
                            description: BackupType defines the type of backup in
                              Velero backups
                            type: string
                          name:
                            type: string
                          schedulePeriod:
                            type: string
                        required:
                        - backupType
                        - name
                        type: object
                      type: array
                    liveStatePackage:
                      description: Selected          bool                `json:"selected"`
                      type: boolean
                    name:
                      type: string
                    packagePath:
                      type: string
                    packageType:
                      description: PackageType defines the type of package (stateless
                        or stateful)
                      type: string
                  required:
                  - backupInformation
                  - name
                  - packagePath
                  - packageType
                  type: object
                type: array
              selectMode:
                type: string
              targetClusterPolicy:
                description: PackageRetentionPolicy PackageRetentionPolicy `json:"packageRetentionPolicy,omitempty"`
                properties:
                  avoidClusters:
                    items:
                      properties:
                        name:
                          type: string
                        repoType:
                          description: |-
                            Repo string `json:"repo"`
                            RepoType is the type of repository (e.g., git, helm)
                          type: string
                        weight:
                          description: Weight is used to prioritize clusters, higher
                            values indicate higher preference
                          type: integer
                      required:
                      - name
                      - repoType
                      type: object
                    type: array
                  preferClusters:
                    items:
                      properties:
                        name:
                          type: string
                        repoType:
                          description: |-
                            Repo string `json:"repo"`
                            RepoType is the type of repository (e.g., git, helm)
                          type: string
                        weight:
                          description: Weight is used to prioritize clusters, higher
                            values indicate higher preference
                          type: integer
                      required:
                      - name
                      - repoType
                      type: object
                    type: array
                type: object
            required:
            - clusterSelector
            - selectMode
            type: object
          status:
            properties:
              transitionedPackages:
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    packageSelectors:
                      items:
                        description: PackageSelector defines individual package selection
                          criteria
                        properties:
                          backupInformation:
                            items:
                              properties:
                                backupType:
                                  description: BackupType defines the type of backup
                                    in Velero backups
                                  type: string
                                name:
                                  type: string
                                schedulePeriod:
                                  type: string
                              required:
                              - backupType
                              - name
                              type: object
                            type: array
                          liveStatePackage:
                            description: Selected          bool                `json:"selected"`
                            type: boolean
                          name:
                            type: string
                          packagePath:
                            type: string
                          packageType:
                            description: PackageType defines the type of package (stateless
                              or stateful)
                            type: string
                        required:
                        - backupInformation
                        - name
                        - packagePath
                        - packageType
                        type: object
                      type: array
                    packageTransitionCondition:
                      type: string
                    packageTransitionMessage:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
